Feat/187: Embed fonts in application and fix/185: Get project ubuntu ready
s-blu/writerey pull request #190
Opened 2020-11-08 10:34 UTC by diegopf

First PR! :) 
Closes #187 and fixes #185

2020-11-08 19:27 UTC, s-blu requested changes
The app is now using Roboto in different font weights - depending on the material css - and not everywhere in 300 anymore, like before, simply because it was the only weight available. 

Not sure how we could fix that. Maybe embeding only the 300 weight as the font file? Since material is overwriting that everywhere it seems like a hassle to solve that css wise

2020-11-08 19:27 UTC, s-blu commented on src/index.html
> -    <link href="https://fonts.googleapis.com/css?family=Noto+Serif|Roboto:300&display=swap" rel="stylesheet" />
Yay, I can complain at other peoples work now _also_ on my free time!!
We'd not only need Roboto, but also Noto Serif, which is used as the font for the editor. :)

2020-11-08 19:27 UTC, s-blu commented on server/initialize_env.py
> +# TODO: is this package named pip under ubuntu, too?
Oopsie, my bad. Could you remove that for me?

2020-11-10 19:10 UTC, diegopf commented
@s-blu not sure why but I don't have the problem with Roboto on my machine. I didn't see a difference between development and this branch. Anyway, I've adjusted the configuration to load Roboto and now everything should look the same (I hope! :D)

2020-11-11 19:11 UTC, s-blu approved these changes

2020-11-11 20:25 UTC, merged